### ISSUE TITLE
Markdown starting BOLD embedded in ITALICS renders wrongly within the editor

### ISSUE THREAD

**Issue by JesseSteele** [microsoft/vscode-markdown-tm-grammar#159] opened 2024-03-13 19:27 UTC
Does this issue occur when all extensions are disabled?: Yes

- VS Code Version: 1.87.2
- OS Version: Linux x64 6.1.77-2-MANJARO

# Problem:
- This is ***not*** about Markdown rendered on a page.
- This is about Markdown rendered inside the editor.

Steps to Reproduce:

1. Copy-paste the following code block into any markdown file:

```
- Incorrectly rendered in the editor:

***Chocolate** and **cookies** are separate topics*
***Starting Bold** and **then more bold** in an asterisk italics line, but the entire line should appear as italics*
___Starting Bold__ and __then more bold__ in an underscore italics line, but as plain text when the line is italics_
***Starting bold** without more bold in an asterisk italics line also renders incorrectly: as bold when the line is italics*
___Starting bold__ without more bold in an underscore italics line also renders incorrectly: as plain text when the line is italics_

- Correctly rendered in the editor:

_**Chocolate** and **cookies** are separate topics_
***Chocolate* and *cookies* are separate topics** - as an asterisk bold line
__*Chocolate* and *cookies* are separate topics__ - as an underscore bold line
***Starting italics* with asterisk italics inside an asterisk bold line renders the line correctly in the editor: as a bold line**
**_Starting italics_ with underscore italics inside an asterisk bold line renders the line correctly in the editor: as a bold line**
*One **bold** word deep inside asterisk italics renders the line correctly **and sometimes bold** in the editor*
_One **bold** word deep inside underscore italics renders the line correctly **and sometimes bold** in the editor_
**A bold line *with asterisk italics deep inside* renders the line correctly *with more italics* in the editor**
**A bold line _with underscore italics deep inside_ renders the line correctly _with more italics_ in the editor**
```

**Comment by mjbvz** [comment] 2024-03-20 21:08
Duplicate of #69

**Closed by mjbvz** 2024-03-20 21:08 UTC
