### ISSUE TITLE
Inline code blocks broken over multiple lines are not highlighted correctly.

### ISSUE THREAD

**Issue by a-stewart** [microsoft/vscode-markdown-tm-grammar#144] opened 2023-08-09 18:19 UTC
The following code is valid markdown (at least on github and VS Code previews)

~~~
Run the command `myCommand
--help` for more infomation.
~~~

It looks as follows:

Run the command `myCommand
--help` for more infomation.

The same is also true for bold and italics. However, the syntax highlighting in VS Code does not seem to support line breaks in these situations.

![image](https://github.com/microsoft/vscode-markdown-tm-grammar/assets/150152/2a283a52-e295-4755-8d0d-cd262c209a3a)

The preview on the right shows VS Codes markdown rendering will preview them correctly, but as shown on the left, it won't highlight them as expected.

**Comment by mjbvz** [comment] 2023-08-09 18:29
Duplicate of #36

**Closed by mjbvz** 2023-08-09 18:29 UTC
